openapi: 3.0.3
info:
  title: OpenAPI schema for template .
components:
  schemas:
    variables:
      type: object
      properties:
        release_name:
          title: Release Name
          type: string
          description: The name of the Helm release.
          default: victoria-logs-single
          x-walrus-ui:
            group: Basic
            order: 1
        namespace_name:
          title: Namespace Name
          type: string
          description: The namespace where the Helm release will be installed.
          default: victoria-system
          x-walrus-ui:
            group: Basic
            order: 2
        chart_version:
          title: Chart Version
          type: string
          description: The version of the victoria-logs-single Helm chart.
          default: 0.8.11
          x-walrus-ui:
            group: Basic
            order: 3
        victoria_logs_image:
          title: Victoria Logs Image
          type: string
          description: The victoria logs image version.
          default: v0.15.0-victorialogs
          x-walrus-ui:
            group: Basic
            order: 4
        resources:
          title: Resources
          type: object
          description: Resource limits and requests for the Helm release.
          default:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          additionalProperties:
            additionalProperties:
              type: string
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 5
      x-walrus-ui:
        groupOrder:
        - Basic
